= Apache Shiro 1.4.0-RC2 Released
Brian Demers
:jbake-date: 2016-11-14 00:00:00
:jbake-type: post
:jbake-status: published
:jbake-tags: blog
:idprefix:
:icons: font

The Shiro team is pleased to announce the release of Apache Shiro version 1.4.0-RC2. This is a feature release for 1.x.

This release includes 15 issues resolved since the 1.3.2 release and is available for Download now.

Of Note:

* The core has been broken up into a fewer smaller modules (lang, crypto, config), but package names remain the same.
Maven, Gradle, and Ivy users will NOT be affected.
* New https://github.com/apache/shiro/tree/shiro-root-1.4.0-RC2/support/spring-boot[modules] for Spring Boot
* New http://search.maven.org/#artifactdetails%7Corg.apache.shiro%7Cshiro-servlet-plugin%7C1.4.0-RC2%7Cjar[servlet fragment module]
* New module for JAX-RS (based off https://github.com/silb/shiro-jersey)
* Guice 4 support
* Shiro.ini string interpolation

This release is an release candidate, so we encourage feedback on the new modules above.

Release binaries (.jars) are also available through Maven Central and source bundles through Apache distribution mirrors.

For more information on link:/documentation.html[Shiro, please read the documentation.]

Enjoy!

The Apache Shiro Team
