= Apache Shiro becomes an Apache Top Level Project
Les Hazlewood
:jbake-date: 2010-09-24
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, apache
:idprefix:

On Wednesday, September 22nd jbake.content.blog.2010, the Apache Software Foundation Board voted unanimously to accept Apache Shiro's graduation out of the Incubator and to become a Apache Top Level Project.

Many thanks to the entire community for the continued growth and support, and especially to our Mentors, for helping us navigate the project through the incubation process.
Everything is much appreciated and it has been well worth it.

Next steps:  It will take us a bit of time to migrate our infrastructure to non-Incubator resources (shiro.apache.org subdomain, Subversion move, etc), so please stay tuned.
Hopefully that can be done in the next two weeks.  Shortly thereafter, we hope to release Shiro 1.1.

Thanks again to all, and please keep contributing to the project and the mailing lists to continually better the project for everyone!

Best regards,

Les
