= Apache Shiro 1.2.1 Released
Les Hazlewood
:jbake-date: 2012-07-29 00:00:00
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, release
:idprefix:

Dear Apache Shiro Community,

The Shiro team is pleased to announce the release of Apache Shiro version 1.2.1.
This is the first bug fix point release after 1.2.0.

This release includes link:https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310950&amp;version=12319511[11 bug fixes] since the 1.2.0 release and is available for link:/download.html[Download] now.

All binaries (`.jars`) are available in Maven Central already.
Please note that the Apache mirrors are still updating to reflect the source distribution, but some mirrors may not be updated yet.
If a mirror download link does not work, please try another or wait another 12 to 24 hours.

For more information on Shiro 1.2, please read the "link:https://stormpath.com/blog/whats-new-apache-shiro-12[What's new in Apache Shiro 1.2?]" article or the previous link:/blog/2012/01/24/apache-shiro-120-released.html[1.2 release announcement].

Enjoy!

The Apache Shiro Team
