= Apache Shiro 1.1.0 Released
Les Hazlewood
:jbake-date: 2010-11-03 00:00:00
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, release
:idprefix:

Dear Apache Shiro Community,

We are proud and excited to offer Apache Shiro's first release as an Apache Top Level Project, Apache Shiro version 1.1.0.

This release includes a number of bug fixes, new features and one important security vulnerability fix - it is recommended that users upgrade to 1.1.0 as soon as possible.

Version 1.1.0 is available immediately for download link:/download.html[here] accompanied by link:/documentation.html[associated documentation] and link:https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12314742&amp;styleName=Html&amp;projectId=12310950[Release Notes].

All binaries are available in Maven Central already.
Please note that most of the Apache mirrors have been updated to reflect the source distribution, but some mirrors may not be updated yet.
If a mirror download link does not work, please try another or wait another 12 to 24 hours.

Enjoy!
