= About Apache Shiro
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: documentation, about
:idprefix:

Apache Shiro is a top level open source project under the https://www.apache.org[Apache Software Foundation].
As a project, Shiro is an application security framework that provides application developers very clean and simple ways of supporting four cornerstones of security in their applications: authentication, authorization, enterprise session management and cryptography.

If you'd like to learn more about Shiro please visit the links below

* link:what-is-shiro.html[What is Shiro] - A deeper look into the project, its mission, and its history

* link:features.html[Features] - Explore the major features of the project

* link:../../news.html[News] - Stay up to date on the latest Apache Shiro news

* link:events.html[Events] - See what Apache Shiro events are coming that you should consider attending

* link:license.html[License] - Review the license under which Shiro is released - Apache Software License, Version 2.0