= Commercial Support for Apache Shiro
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: documentation, support, services, commercial
:idprefix:
:icons: font

Apache Shiro is a widely used project. As such, several companies have built products and services around Shiro. This page is dedicated to providing descriptions of those offerings and links to more information. The products and services listed on this page are provided for information use only to our users. The Apache Shiro PMC does not endorse or recommend any of the products or services on this page.

== Flow Logix
link:https://flowlogix.com/[Flow Logix] provides commercial support, products and consulting services for Apache Shiro, Jakarta EE (formerly Java EE) and related projects.

link:https://flowlogix.com/services.html[Learn More >>>]

== Yupiik

link:https://www.yupiik.com/[Yupiik] provides commercial support, products and consulting services for Apache Shiro and related projects.

link:https://www.yupiik.com/production-support/[Learn More >>>]

== Policy for additions to this page

Companies are free to add information about their products and services to this page (please keep entries in alphabetical order). The information must be factual and informational in nature and not be a marketing statement. Statements that promote your products and services over other offerings on the page will not be tolerated and will be removed. Such marketing statements can be added to your own pages on your own site, but not here.

When in doubt, email the Shiro dev list (see link:mailing-lists.html[Mailing Lists]) and ask. We would be happy to help.
