[#DeveloperResources-ApacheShiroDeveloperResources]
= Apache Shiro Developer Resources
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: development, git, clone, main, master, trunk, mavne
:idprefix:
:icons: font

This page is dedicated for reference information used by the Apache Shiro development team when performing tasks as a committer or contributor.

[#DeveloperResources-WritingDocumentation]
== Writing Documentation

All non-JavaDoc documentation is managed in our https://github.com/apache/shiro-site[apache/shiro-site] repo.

[#DeveloperResources-SourceCodeRepository]
== Source Code Repository

We use a Git repository located at git://git.apache.org/shiro.git.
You can also browse the mirrored repository on GitHub, located at link:https://github.com/apache/shiro-site[].

Active development is done in the `main` branch, and maintenance typically on the `1.N.x` branch (where `N` is the current feature release and `x` is static).

[#DeveloperResources-BuildingfromGit]
=== Building from Git

For Shiro cutting-edge development, you can clone the code from Git and build it using https://maven.apache.org[Maven] 3.6+:

1. Check out the code:
+
[source,bash]
----
git clone https://github.com/apache/shiro.git
----
2. Build the project using https://maven.apache.org[Maven] 3.6+:
+
[source,bash]
----
cd shiro
mvn verify
----

[CAUTION]
.Cutting-edge development
====
When building from `main` or any branches, use the generated artifacts at your own risk!
Current and previous stable releases will always be available via the link:/download.html[Download] page.
====
