= Get Started with Apache Shiro
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: getting-started, tutorial, beginner, quickstart
:jbake-description: Get started with Apache Shiro security framework. Learn the basics of authentication, authorization, cryptography, and session management with links to tutorials and guides.
:idprefix:

Apache Shiro focuses on ease-of-use, so you can rely on secure, stable authentication, authorization, cryptography, and session management. With Shiro’s easy-to-understand API, you can quickly and easily secure any application. Get started!

== The Basics

* *link:introduction.html[Introduction to the Apache Shiro Java Security Framework]*
A high-level overview of Apache Shiro's capabilities.

* *link:architecture.html[Architecture]*
An architectural overview of Apache Shiro.

* *link:terminology.html[Terminology]*
A list of definitions of common security concepts and concerns.

* *link:what-is-shiro.html[Apache Shiro Project Background]*
Apache Shiro, like most useful tools, was created out of necessity. Learn more about the project history and mission statement.

== Tutorials

* *link:10-minute-tutorial.html[10-Minute Tutorial]*
Learn all the ins and outs of the Shiro Framework in under 10 minutes. This quick and simple tutorial shows how a developer uses Shiro in their application.

* *link:tutorial.html[Your First Shiro Application]*
If you're new to Apache Shiro, this short tutorial will show you how to set up a very simple application secured by Apache Shiro. We'll discuss Shiro's core concepts along the way to help familiarize you with Shiro's design and API.

== Other Resources

* *link:articles.html[Introductory Articles… and Beyond!]*
Articles and Guides written by and for members of the Apache Shiro community.