= Integrations
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: integrations, spring, guice, jakarta-ee, frameworks
:jbake-description: Apache Shiro integrations with popular frameworks including Spring, Spring Boot, Guice, Jakarta EE, JAX-RS and more.
:idprefix:
:icons: font
:toc:

Shiro has been downloaded over one million times and is in production at thousands of companies. One reason: it integrates well with other technologies and frameworks.

== Officially Supported Integrations

These integrations are supported by the Apache Shiro Development team.
Want to help make them great?
link:/how-to-contribute.html[Contribute] back to the project!

* *link:/spring.html[Spring Application Framework]*
+
Integrate Shiro into standalone or web-based Spring applications.

* *link:/guice.html[Guice Dependency Injection Framework]*
+
For Guice-based applications using standard Guice conventions and mechanisms.

* *link:/cas.html[CAS SSO server]*
+
Protect your WebApp with a Jasig CAS SSO server.

== Open Source Community Integrations

* *https://github.com/bujiio/buji-pac4j[buji-pac4j]*
+
from https://www.pac4j.org/[PAC4J]
+
An easy and powerful security library for Shiro web applications and web services.

* *https://plugins.grails.org/plugin/nerderg/grails-shiroo[Grails]*
+
from https://nerderg.com/[nerdEng].
+
Adds easy authentication and access control to Grails applications.

* *https://isis.apache.org[Apache Isis]*
+
from https://apache.org/[Apache].
+
Apache Isis is a full-stack framework for rapidly developing domain driven apps and RESTful APIs in Java.
https://isis.apache.org/documentation.html#security[It uses Apache Shiro] for authentication and authorization.

* *https://geode.apache.org/[Apache Geode]*
+
from https://apache.org/[Apache].
+
Using Apache Shiro to secure Geode endpoints like JMX operations, rest services, web monitoring application, CLI tool, and client server communications.

* *https://github.com/cilogi/gaeshiro[Google App Engine]*
+
from https://twitter.com/@cilogi[@cilogi].
+
Demo of one way to integrate Shiro with App Engine and Google Guice, plus front-end user registration and password management.

* *https://github.com/55minutes/fiftyfive-wicket[55Wicket]*
+
from https://55minutes.com[55 Minutes]
+
A nifty set of tools and libraries for enhancing productivity with the Apache Wicket Java web framework, including Shiro Integration.

* *https://github.com/timperrett/lift-shiro[Lift]*
+
from https://twitter.com/@timperrett[@timperrett].
+
Integration between Shiro and the Lift Web framework.
Uses Lift’s sitemap Locs instead of Shiro’s built-in web.xml resource filters to control access to URLs.

* *https://github.com/alexxiyang/shiro-redis[Redis Cache Manager]*
+
from https://github.com/alexxiyang[@alexxiyang].
+
A https://redis.io/[Redis] Cache Manager implementation.

* *https://github.com/mythfish/shiro-memcached[Memcached Cache Manager]*
+
from https://github.com/mythfish[@mythfish]
+
A https://memcached.org/[Memcached] Cache Manager implementation.

* *https://github.com/silb/shiro-jersey[JAX-RS]*
+
from https://github.com/silb[@silb].
+
Apache Shiro support for the Jersey JAX-RS implementation.

NOTE: This module had been moved into Apache Shiro.

* *https://github.com/silb/dropwizard-shiro[Dropwizard]*
+
from https://github.com/silb[@silb].
+
A bundle for securing https://www.dropwizard.io/[Dropwizard] with Apache Shiro.

* *https://github.com/theborakompanioni/thymeleaf-extras-shiro[Thymeleaf]*
+
from https://github.com/theborakompanioni[@theborakompanioni].
+
A https://www.thymeleaf.org/[Thymeleaf] dialect for https://shiro.apache.org[Apache Shiro] https://shiro.apache.org/tags[tags].

* *https://github.com/davidsowerby/krail[Krail]*
+
from https://github.com/davidsowerby[@davidsowerby].
+
Krail provides a framework for rapid Java web development by combining Vaadin, Guice, Apache Shiro, Apache Commons Configuration and others.

* *https://github.com/ocpsoft/rewrite/tree/main/security-integration-shiro[Rewrite Servlet]*
+
from https://www.ocpsoft.org/rewrite/[ocpsoft].
+
A highly configurable URL-rewriting tool for Java EE 6+ and Servlet 2.5+ applications

* *https://freedomotic-developer-manual.readthedocs.io/en/latest/plugins/security.html[Freedomotic]*
+
from https://www.freedomotic.com[freedomotic].
+
An open source, flexible, secure Internet of Things (IoT) development framework in Java, useful to build and manage modern smart spaces.

* *https://github.com/flowlogix/flowlogix[FlowLogix Jakarta EE Library]*
+
from https://twitter.com/lprimak[Lenny Primak].
+
Integrates Jakarta EE / Java EE applications with Shiro Security, specifically makes Shiro Annotations work with Java EE.

NOTE: This module will be integrated directly into Shiro with version 2.0 and above.

* *https://github.com/bootique/bootique-shiro[Bootique Shiro]*
+
from https://github.com/bootique/bootique[Bootique].
+
Bootique is a minimally opinionated platform for modern runnable Java apps.

* *https://github.com/casdoor/shiro-casdoor[Shiro Casdoor]*
+
from https://casdoor.org/[Casdoor].
+
Casdoor is a UI-first centralized authentication / Single-Sign-On (SSO) platform supporting OAuth 2.0, OIDC and SAML.


== Ports

* *https://github.com/stormpath/Turnstile[Turnstile]* - Swift

* *https://github.com/YosaiProject/yosai[Yosai]* - Python

* *https://github.com/gnavarro77/angular-shiro[Angular]* - Angular

== Got An Integration?

Have an integration you want listed?
Send us a pull request of https://github.com/apache/shiro-site/blob/main/integration.md[this page], and participate in Shiro development!

link:how-to-contribute.html[Learn more about contributing to Apache Shiro].
