= Apache Shiro Bug &amp; Issue Tracking
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: issues, bugs, jira, bug-tracking, support
:jbake-description: Report bugs, request features, and track issues for Apache Shiro using GitHub Issues tracking system.
:idprefix:
:icons: font

Apache Shiro uses https://github.com/apache/shiro/issues[GitHub Issues] for bug reports, feature requests, and task tracking.

For questions, ideas, and community discussions, please use https://github.com/apache/shiro/discussions[GitHub Discussions].

== Usage Guidelines

GitHub Issues is provided as a Shiro software development resource.
It is meant for reporting bugs, requesting features, and tracking improvements in the software itself - it is not a support portal to ask for advice or help.
For community advice and help in using Apache Shiro, please visit the link:/support.html[Support] page or use https://github.com/apache/shiro/discussions[GitHub Discussions].

*Prior to opening an issue, we ask that:*

* You do your due diligence to ensure a suspected error is actually a bug.
* You search the issue tracker to ensure what you want to report has not already been reported by someone else.
* If your problem is actually a bug, we would appreciate it if you could attach a simple JUnit test case that allows us to repeat the problem, so we can fix it as fast as possible.
* If a unit test is not available (please really try to make one!), attach a stack trace and Shiro's TRACE or DEBUG log output.
* If you've already fixed the problem, please submit a pull request, and we'll likely include it in the next release.

https://github.com/apache/shiro/issues[Click here to visit the Apache Shiro GitHub Issues tracker].

== JIRA (Legacy)

JIRA is retained for archival purposes only and is no longer used for new issues.

https://issues.apache.org/jira/browse/SHIRO[Click here to visit the legacy Apache Shiro JIRA issue tracker].
