= Apache Shiro Bug &amp; Issue Tracking
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: documentation, support, community, issues, bugs
:idprefix:
:icons: font

Apache Shiro uses Atlassian Jira for tracking tasks, feature requests, bugs, and other issues related to the project development.

== Usage Guidelines

Jira is provided as a Shiro software development resource.
It is meant to be for managing bugs, tasks and improvements in the software itself - it is not a support portal to ask for advice or help.
For community advice and help in using Apache Shiro, please visit the link:/support.html[Support] page.

*Prior to using Jira, we ask that:*

* You do your due diligence to ensure a suspected error is actually a bug.
* You search the issue tracker to ensure what you want to report has not already been reported by someone else.
* If your problem is actually a bug, we would appreciate it if you could attach a simple JUnit test case that allows us to repeat the problem, so we can fix it as fast as possible.
* If a unit test is not available (please really try to make one!), attach a stack trace and Shiro's TRACE or DEBUG log output.
* If you've already fixed the problem, please submit a patch, and we'll likely include it in the next release.

https://issues.apache.org/jira/browse/SHIRO[Click here to visit the Apache Shiro Jira issue tracker].
