= Roadmap
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: events, meetings
:idprefix:
:icons: font
:toc:

We currently do not have a timeline for version 2, but we are already collecting ideas.
New features are implemented into the "main" branch every now and then.

You can find the complete list of ideas in our wiki: link:https://cwiki.apache.org/confluence/display/SHIRO/Version+2+Brainstorming[Version 2 Brainstorming].

[IMPORTANT]
====
This list is not exhaustive.
The wiki page should be regarded as the primary source.
Feel free to tell us about your ideas on the link:mailing-lists.html[mailing lists]!
====

== Excerpt of Version 2 features

* Event support

* Authorization ANTLR Grammar

* Multi-Stage Authentication via request/response
+
In applications that need to authenticate via multiple mechanisms (e.g. multi-factor authentication), a Request/Response protocol for login would probably be easier to use to support such workflows.

* Captcha Support

== Excerpt of Version 2 changes


* Rename AuthenticationInfo to Account

* Realm refactoring

* New layout of maven modules

* Redefine Component Names
+
Change classes named FooDAO to FooStore instead.
