= Apache Shiro Community Support
:jbake-date: 2010-03-18 00:00:00
:jbake-type: page
:jbake-status: published
:jbake-tags: documentation, support, community, mailing lists, forums, issues, bugs
:idprefix:
:icons: font

The Shiro project offers support through its community of users, contributors, and project committers.

We encourage everyone to participate and use the available community support tools below.

* link:troubleshooting.html[Troubleshooting & FAQ]
* link:mailing-lists.html[Mailing Lists]
* link:forums.html[Forums]
* link:issues.html[Issues and Bug Tracking]
* link:commercial-support.html[Commercial Support]

== Sponsorship

Sponsorship can be used simply as a way to say thank you for the work that has been done
or as a way to encourage specific issues to be worked on.
In either case, while the Apache Shiro project thanks you for your support,
we cannot be responsible for any promises and/or contributions made by an individual committer,
as individual commits must be reviewed and accepted by the project team.

=== Committers accepting GitHub Sponsorship
* https://github.com/sponsors/bmarwell[Benjamin Marwell]
* https://github.com/sponsors/lprimak/[Lenny Primak]
